name: release.yml

on:
  push:
    tags:
      - '*.*.*' # Trigger on version tags like 1.0.0

jobs:
  release:
    runs-on: ubuntu-22.04

    steps:
      - uses: actions/checkout@v4

      - name: Fix sources.list to support arm64
        run: |
          sudo sed -i 's|^deb http://|deb [arch=amd64,arm64] http://|g' /etc/apt/sources.list
          sudo sed -i 's|^deb https://|deb [arch=amd64,arm64] https://|g' /etc/apt/sources.list

      - name: Set up Build Environment
        run: |
          sudo dpkg --add-architecture arm64
          sudo apt-get update
          sudo apt-get install -y build-essential devscripts dh-systemd fakeroot \
            python-all python-docutils iproute2 python-ipaddr python-setuptools \
            dh-python python3-all python3-setuptools python3-docutils ethtool \
            bridge-utils python-gvgen python-mako

      - name: Build Package
        run: make deb
