name: release.yml

on:
  push:
    tags:
      - '*.*.*' # Trigger on version tags like 1.0.0

jobs:
  release:
    runs-on: ubuntu-22.04

    steps:
      - uses: actions/checkout@v4

      - name: Set up Build Environment
        run: |
          # amd64 only
          sudo tee /etc/apt/sources.list <<EOF
          deb [arch=amd64] http://archive.ubuntu.com/ubuntu jammy main restricted universe multiverse
          deb [arch=amd64] http://archive.ubuntu.com/ubuntu jammy-updates main restricted universe multiverse
          deb [arch=amd64] http://archive.ubuntu.com/ubuntu jammy-backports main restricted universe multiverse
          deb [arch=amd64] http://security.ubuntu.com/ubuntu jammy-security main restricted universe multiverse
          deb [arch=amd64] http://archive.canonical.com/ubuntu jammy partner
          EOF
  
          # arm64 only
          sudo tee /etc/apt/sources.list.d/arm64.list <<EOF
          deb [arch=arm64] http://ports.ubuntu.com/ubuntu-ports jammy main restricted universe multiverse
          deb [arch=arm64] http://ports.ubuntu.com/ubuntu-ports jammy-updates main restricted universe multiverse
          deb [arch=arm64] http://ports.ubuntu.com/ubuntu-ports jammy-backports main restricted universe multiverse
          deb [arch=arm64] http://ports.ubuntu.com/ubuntu-ports jammy-security main restricted universe multiverse
          deb [arch=arm64] http://archive.canonical.com/ubuntu jammy partner
          EOF

      - name: Set up Build Environment
        run: |
          sudo dpkg --add-architecture arm64
          sudo apt-get update
          sudo apt-get install -y build-essential devscripts fakeroot \
            python-all python3-docutils iproute2 python-setuptools \
            dh-python python3-all python3-setuptools python3-docutils ethtool \
            bridge-utils python3-mako

      - name: Build Package
        run: make deb
